include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: info
    invalid_annotation_target: ignore

  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
linter:
  rules:
    require_trailing_commas: true
